# Generated by Django 2.2.6 on 2019-10-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
