# Generated by Django 2.2.6 on 2019-10-23 01:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 1, 32, 49, 800180, tzinfo=utc)),
        ),
    ]
